name: build employee-registration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build employee-registration-module
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        env:
          MESSAGE: Hello world message
        run: echo $MESSAGE
      - name: check-out the code
        uses: actions/checkout@v4