name: build employee-registration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build employee-registration-module
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        env:
          MESSAGE: Hello world message
        run: echo $MESSAGE
      - name: check-out the code
        uses: actions/checkout@v4
      - name: build the project
        run: mvn clean install
      - name: push docker image to ACR
        run:|
          echo "${{ secrets.NARYA_ACR_REGISTRY}}" | docker login -u naryaAcrRegistry -p "${{ secrets.NARYA_ACR_REGISTRY}}" naryaacrregistry.azurecr.io
          docker build -t employee-registration:20250511 .
          docker tag employee-registration:20250511 naryaacrregistry.azurecr.io/employee-registration:20250511
          docker push naryaacrregistry.azurecr.io/employee-registration:20250511